### ISSUE TITLE
Building assets makes some xblocks lose their assets.

### ISSUE THREAD

**Issue by frob** [regisb/openedx-docker#95]
## Steps to reproduce

Running a stock edx-docker. 

1. Enable comprehensive theming. 
1. Install [image-explorer](https://github.com/edx-solutions/xblock-image-explorer) xblock. 
1. Add an image-explorer xblock to a course.
1. Build assets.

## Unexpected behavior

Whichever environment built last (cms or lms) is the one that will work. The JS asset will load and work properly in that environment. So if I build the assets for lms, then the cms will break. If I build the assets for the cms then the lms will break.

The broken environment will get a 404 error for the xblock js.

## Additional info (IMPORTANT)

```
docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:22 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     false
-------------------------
docker-compose --version
docker-compose version 1.23.1, build b02f130
-------------------------
echo $EDX_PLATFORM_PATH

echo $EDX_PLATFORM_SETTINGS
```

**Comment by regisb** [comment]
What do yo mean by "breaking"? What is the observed incorrect behaviour?

**Comment by frob** [comment]
> Also, how do you build assets?

By running `make assets` or `make assets-lms` or `make assets-cms`.

> What do yo mean by "breaking"? What is the observed incorrect behaviour?

running `make assets-lms` will break the cms.

running `make assets-cms` will break the lms.

running `make assets` breaks which ever service builds first. This might be an artifact of the comprehensive theming.

**Comment by regisb** [comment]
Do you mean that static assets are no longer loaded in the lms/cms because they result in 404 errors?

**Comment by frob** [comment]
yes

**Comment by frob** [comment]
> which modifications did you make to docker-compose.yml to enable comprehensive theming?

I added a bind mount from `src/theme/custom` to `/openedx/edx-platform/themes/custom`

**Comment by frob** [comment]
I have done some digging.  

I see `/data/cms` and `/data/lms` are sharing the same data on the containers as `/openedx/data`.

I have also confirmed that building the assets for both lms and cms while logged into the lms via `make lms` will add the file to the `/data/cms/staticfiles/xblock/resources/image_explorer/public/css/` but not the corresponding `data/lms` directory.

Why are we using two different directories for the static data in lms and cms static files?

**Comment by frob** [comment]
Another update, I just noticed that it is only css and not js that is returning 404.

**Comment by regisb** [comment]
Is it just the CSS from the newly added xblock that result in 404, or CSS for the entire platform? I'm asking, because I just realised that, in your comment on an [earlier issue](https://github.com/regisb/openedx-docker/issues/36#issuecomment-438340541), you mounted an xblocks folder in the container:

```
volumes:
    - ./src/openedx-platform/xblocks/custom:/openedx/edx-platform/xblocks/custom
    - ./src/openedx-platform/xblocks/contrib:/openedx/edx-platform/xblocks/contrib
```

AFAIU, this is the only shared data between the lms and the cms. This is important because commands executed inside the cms should *not* affect data in the lms, because, in the base configuration, there is no volume in common. Which is the reason why I have so much trouble debugging this issue: I simply can't see how your issue could happen. Would you mind pasting here your entire docker-compose service configuration for the lms and the cms?

**Comment by frob** [comment]
To help debug and figure out if this issue was the caused by something I changed, I rebuilt and removed all that. Also, now that we have private.txt being loaded I wanted to test the way I am installing xblocks.

So this is happening with a new build based on master with the old addition being: the installed xblock, the mounted theme directory, and enabling comprehensive theming.

```
version: "3"
services:

  ############# External services

  memcached:
    image: memcached:1.4.38
    restart: unless-stopped

  mongodb:
    image: mongo:3.2.16
    # Use WiredTiger in all environments, just like at edx.org
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger
    restart: unless-stopped
    volumes:
      - ./data/mongodb:/data/db

  mysql:
    image: mysql:5.6.36
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file: ./config/mysql/auth.env

  elasticsearch:
    image: elasticsearch:1.5.2
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.name=openedx"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  nginx:
    image: nginx:1.13
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d/
      - ./data/lms:/openedx/data/lms:ro
      - ./data/cms:/openedx/data/cms:ro
      - ./data/letsencrypt:/etc/letsencrypt/:ro

  rabbitmq:
    image: rabbitmq:3.6.10
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped

  # Simple SMTP server
  smtp:
    image: namshi/smtp
    restart: unless-stopped

  ############# Forum

  forum:
    image: regis/openedx-forum:hawthorn
    build:
      context: ./forum
    environment:
      API_KEY: "forumapikey"
      SEARCH_SERVER: "http://elasticsearch:9200"
      MONGOHQ_URL: "mongodb://mongodb/cs_comments_service"
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - mongodb

  ############# LMS and CMS

  lms:
    image: regis/openedx:hawthorn
    build:
      context: ./openedx
    environment:
      SERVICE_VARIANT: lms
    restart: unless-stopped
    volumes:
      - ./config/openedx:/openedx/config
      - ./data/lms:/openedx/data
      - ./src/themes/custom:/openedx/edx-platform/themes/custom
    depends_on:
      - elasticsearch
      - forum
      - memcached
      - mongodb
      - mysql
      - rabbitmq
      - smtp

  cms:
    image: regis/openedx:hawthorn
    build:
      context: ./openedx
    environment:
      SERVICE_VARIANT: cms
    restart: unless-stopped
    volumes:
      - ./config/openedx:/openedx/config
      - ./data/cms:/openedx/data
      - ./src/themes/custom:/openedx/edx-platform/themes/custom
    depends_on:
      - memcached
      - mongodb
      - mysql
      - rabbitmq
      - smtp

  ############# LMS and CMS workers

  # We could probably create one service per queue here. For small instances, it is not necessary.
  lms_worker:
    image: regis/openedx:hawthorn
    build:
      context: ./openedx
    environment:
      SERVICE_VARIANT: lms
      C_FORCE_ROOT: "1" # run celery tasks as root #nofear
    command: ./manage.py lms celery worker --loglevel=info --hostname=edx.lms.core.default.%%h --maxtasksperchild 100
    restart: unless-stopped
    volumes:
      - ./config/openedx:/openedx/config
      - ./data/lms:/openedx/data
      - ./src/themes/custom:/openedx/edx-platform/themes/custom
    depends_on:
      - lms

  cms_worker:
    image: regis/openedx:hawthorn
    build:
      context: ./openedx
    environment:
      SERVICE_VARIANT: cms
      C_FORCE_ROOT: "1" # run celery tasks as root #nofear
    command: ./manage.py cms celery worker --loglevel=info --hostname=edx.cms.core.default.%%h --maxtasksperchild 100
    restart: unless-stopped
    volumes:
      - ./config/openedx:/openedx/config
      - ./data/cms:/openedx/data
      - ./src/themes/custom:/openedx/edx-platform/themes/custom
    depends_on:
      - cms
```

It is now also the images from that xblock. I expect there is other stuff that I have just missed that isn't loading. As a workaround I have changed the nginx try_files rules to include the files from the lms/cms.

`lms.conf` for nginx example modification:

original

```
  location ~ ^/static/(?P<file>.*) {
    root /openedx/data/lms;
    try_files /staticfiles/$file /course_static/$file =404;
...
}
```

modified

```
  location ~ ^/static/(?P<file>.*) {
    root /openedx/data;
    try_files /lms/staticfiles/$file /lms/course_static/$file /cms/staticfiles/studio/$file =404;
...
}
```

It is as though the static asset is being created with the wrong apps cache busting hash. I have not yet dug into the webpack configuration to see what is generating the hash.
